# Generated by Django 4.1.3 on 2022-11-24 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0002_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='currency',
        ),
    ]
